c_compiler_version:            # [linux or osx]
  - 11                         # [linux]
  - 12                         # [osx]
cxx_compiler_version:          # [linux or linux]
  - 11                         # [linux]
  - 12                         # [osx]
