c_compiler_version:
  - 11                         # [linux]
  - 12                         # [osx]
cxx_compiler_version:
  - 11                         # [linux]
  - 12                         # [osx]
