{% set version = "2.0.10" %}

package:
  name: atheris
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/atheris/atheris-{{ version }}.tar.gz
  sha256: c387fac19e49c7c1b4d3ca125164ee69e6dc63a12bc2e7fe8c8527c233f0cba0

build:
  number: 0
  skip: true  # [py<37 or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils  # [unix]
    - clangxx
    - compiler-rt_{{ target_platform }}
  host:
    - pip
    - pybind11 >=2.5.0
    - python
  run:
    - python

test:
  source_files:
    - example_fuzzers/fuzzing_example.py
    - example_fuzzers/example_library.py
  imports:
    - atheris
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/atheris/
  summary: A coverage-guided fuzzer for Python and Python extensions.
  license: Apache-2.0
  license_file: LICENSE
  description: |-
    Atheris is a coverage-guided Python fuzzing engine. It supports fuzzing of
    Python code, but also native extensions written for CPython. Atheris is based
    off of libFuzzer. When fuzzing native code, Atheris can be used in combination
    with Address Sanitizer or Undefined Behavior Sanitizer to catch extra bugs.

extra:
  recipe-maintainers:
    - bollwyvl
